# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  macos: circleci/macos@2.4.1
  rn: react-native-community/react-native@7.4.0

jobs:
  unit-test:
    docker:
      - image: cimg/node:18.20

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./apps/AEPSampleApp/node_modules

      - run:
          name: Unit Tests
          command: yarn test --watchAll=false --runInBand

  build-sample-app-android:
    executor:
      name: rn/linux_android
      # find the tools installed in the image here: https://hub.docker.com/r/reactnativecommunity/react-native-android/tags
      build_image_version: v13.0
      resource_class: large

    steps:
      - checkout

      - run:
          name: yarn install
          command: yarn install

      - run:
          name: Building Android Sample App
          command: yarn sampleapp:android:build

          environment:
            _JAVA_OPTIONS: "-Xmx4096M -XX:MaxMetaspaceSize=512m"
            
  build-sample-app-android-mac:
    macos:
      xcode: 15.2 # Specify the Xcode version to use

    steps:
      - checkout
      
      - run:
          name: install Android command line tool
          command: brew install --cask android-commandlinetools
      - run:
          name: list Android SDK
          command: sdkmanager --list
      - run: 
          name: accept license
          command: yes | sdkmanager --licenses || if [ $? -ne '141' ]; then exit $?; fi; 
      - run:
          name: install Android SDK
          command: sdkmanager --install "platform-tools" "platforms;android-34" "build-tools;34.0.0" "emulator" 
      - run:
          name: list Android SDK
          command: sdkmanager --list_installed
      - run: 
          name: ss
          command: ls -la ~/Library/Android/sdk
      - run:
          name: yarn install
          command: yarn install
      - run:
          name: Building Android Sample App
          command: yarn sampleapp:android:build
          
  build-sample-app-ios:
    macos:
      xcode: 15.2 # Specify the Xcode version to use

    steps:
      - checkout

      - restore_cache:
          keys:
            - ios-yarn-cache-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: ios-yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./apps/AEPSampleApp/node_modules

      - run:
          name: Install latest Cocoapods
          command: sudo gem install cocoapods

      - run:
          name: Install pods
          command: yarn sampleapp:ios:pod:install

      - run:
          name: Building iOS Sample App
          command: cd apps/AEPSampleApp && npx react-native run-ios --verbose --terminal terminal

workflows:
  version: 2.1
  ci-workflow:
    jobs:
      # - unit-test
      # - build-sample-app-ios
      # - build-sample-app-android
      - build-sample-app-android-mac
