# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  macos: circleci/macos@2.4.1
  react-native: react-native-community/react-native@7.4.0

jobs:
  unit-test:
    docker:
      - image: cimg/node:18.20

    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./apps/AEPSampleApp/node_modules

      - run:
          name: Unit Tests
          command: yarn test --watchAll=false --runInBand

  build-sample-app-android:
    # docker:
    #   - image: cimg/android:2024.01.1-node

    # resource_class: large
    executor: rn/linux_android
    
    steps:
      - checkout

      - run:
          name: yarn install
          command: yarn install

      - run:
          name: Building Android Sample App
          command: |
            export NODE_OPTIONS=--max-old-space-size=8192
            yarn sampleapp:android:build

  build-sample-app-ios:
    macos:
      xcode: 15.2 # Specify the Xcode version to use

    steps:
      - checkout

      # - run:
      #     name: Install latest NodeJS
      #     command: brew install node

      - restore_cache:
          keys:
            - ios-yarn-cache-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: ios-yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
            - ./apps/AEPSampleApp/node_modules

      - run:
          name: Install latest Cocoapods
          command: sudo gem install cocoapods

      - run:
          name: Install pods
          command: yarn sampleapp:ios:pod:install

      - run:
          name: Building iOS Sample App
          command: cd apps/AEPSampleApp && npx react-native run-ios --verbose --terminal terminal

workflows:
  version: 2.1
  ci-workflow:
    jobs:
      - unit-test
      # Uncomment the following lines to build the ios code after this issue is fixed: https://github.com/adobe/aepsdk-react-native/issues/272
      - build-sample-app-ios
      - build-sample-app-android
